import copy
from collections import defaultdict
from collections.abc import Mapping
from typing import Iterator, assert_never

from cvflow.command import Command, CommandKind, N, E, M, X, Z, Node
from cvflow.graph import OpenGraph

import numpy as np

class Pattern:
    """A sequence of commands applied to a graph state.

    Attributes
    ----------
    _commands : list[Command]
        The list of commands in the pattern.
    _input_nodes : set[Node]
        The set of input nodes that are considered initialised at the start of the pattern.

    """
    def __init__(self, commands: list[Command], input_nodes: list[Node]):
        """

        Parameters
        ----------
        commands : list[Command]
            An iterable/sequence of command objects describing the computation.
        input_nodes : list[Node]
            The list of nodes that are considered initialised at the start of the pattern.
        """
        self._commands = commands
        self._input_nodes = set(input_nodes)
        self._nodes = set(input_nodes) | {cmd.node for cmd in commands if cmd.kind == CommandKind.N}
        self._non_input_nodes = self._nodes - self._input_nodes
        self._is_normal_order = self.check_normal_order()

        self.check_runnability()

    @property
    def is_normal_order(self) -> bool:
        """Whether the pattern is in normal order (NEMC).

        A pattern is in normal order if it consists of a sequence of preparation commands (N),
        followed by entanglement commands (E), followed by alternating layers of measurement (M)
        and correction (X, Z) commands, with no interleaving or reordering.

        Patterns generated by ``flow_to_pattern`` are guaranteed to be in normal order.

        Returns
        -------
        bool
            True if the pattern is in normal order, False otherwise.
        """
        return self._is_normal_order

    @property
    def input_nodes(self) -> list[Node]:
        """The set of input nodes that are considered initialised at the start of the pattern."""
        return list(self._input_nodes)

    @property
    def nodes(self) -> list[Node]:
        """The set of all nodes that appear in the pattern."""
        return list(self._nodes)

    @property
    def non_input_nodes(self) -> list[Node]:
        """The set of non-input nodes that need to be prepared by the pattern."""
        return list(self._non_input_nodes)

    @staticmethod
    def from_flow(graph: OpenGraph, g: dict[int, dict[int, float]], layer: dict[int, list[int]]) -> "Pattern":
        """Construct a Pattern from an OpenGraph with a flow.

        This is a convenience wrapper around :func:`flow_to_pattern` that directly constructs the pattern from the graph and its flow.

        Parameters
        ----------
        graph : OpenGraph
            The input graph containing the nodes and edges to be converted.
        g : dict[int, dict[int, float]]
            The flow correction mapping. For each measured node, maps to a
            dictionary of target nodes and their correction amplitudes.
            Structure: {measured_node: {target_node: amplitude}}.
        layer : dict[int, list[int]]
            The layering of nodes for measurement order. Maps layer numbers
            to lists of nodes that should be measured in that layer.
            Structure: {layer_num: [node1, node2, ...]}.
        """
        return flow_to_pattern(graph, g, layer)

    def check_runnability(self):
        """Check if the pattern is runnable.

        A node is initialised if it appears in ``input_nodes`` or has been
        prepared by a preceding ``N`` command. A node is measured once its
        ``M`` command has been executed and it has left the initialised set.

        The following rules are enforced, in command order:

        **N (prepare)**
            The target node must not already be initialised. This catches both
            double-preparation and trying to prepare a node that was declared
            as an input.

        **E (entangle)**
            Both endpoint nodes must be initialised. Applying an entangling gate
            to an unprepared or already-measured node is invalid.

        **M (measure)**
            - The target node must be initialised (not yet measured, not absent).
            - Every node referenced in ``x_domain`` or ``z_domain`` must already
              be measured. This covers two sub-cases: a node whose ``M`` command
              has not yet appeared in the sequence (ordering violation), and a
              node that is never prepared or measured at all (missing node).

        **X / Z (correct)**
            - The target node must be initialised.
            - Every node in the correction domain (``x_domain`` for ``X`` commands,
              ``z_domain`` for ``Z`` commands) must already be measured, with the same
              two sub-cases as for M domain violations above.

        Raises
        ------
        ValueError
            If any of the rules above is violated.
        """
        initialised_nodes = self._input_nodes.copy()
        measured_nodes = set()

        for i, cmd in enumerate(self._commands):
            if cmd.kind == CommandKind.N:
                if cmd.node in initialised_nodes:
                    raise ValueError(f"Node {cmd.node} is already initialised.")
                initialised_nodes.add(cmd.node)
            elif cmd.kind == CommandKind.E:
                if cmd.nodes[0] not in initialised_nodes or cmd.nodes[1] not in initialised_nodes:
                    raise ValueError(f"Entanglement command {cmd} ({i+1}-th command) requires both nodes to be initialised.")
            elif cmd.kind == CommandKind.M:
                if cmd.node not in initialised_nodes:
                    raise ValueError(f"Measurement command {cmd} ({i+1}-th command) requires node {cmd.node} to be initialised.")

                if non_measured_nodes := (cmd.x_domain.keys() | cmd.z_domain.keys()) - measured_nodes:
                    missing_nodes = ",".join(map(str, non_measured_nodes))
                    raise ValueError(f"Measurement command {cmd} ({i+1}-th command) requires node(s) {missing_nodes} to be measured.")

                initialised_nodes.remove(cmd.node)
                measured_nodes.add(cmd.node)
            elif cmd.kind in (CommandKind.X, CommandKind.Z):
                if cmd.node not in initialised_nodes:
                    raise ValueError(f"Correction command {cmd} ({i+1}-th command) requires node {cmd.node} to be initialised.")

                domain = cmd.x_domain.keys() if cmd.kind == CommandKind.X else cmd.z_domain.keys()
                if non_measured_nodes := domain - measured_nodes:
                    missing_nodes = ",".join(map(str, non_measured_nodes))
                    raise ValueError(f"Correction command {cmd} ({i+1}-th command) requires node(s) {missing_nodes} to be measured.")
            else:
                assert_never(cmd.kind)

    def check_normal_order(self) -> bool:
        """Check if the pattern is in normal order (NEMC).

        A pattern is in normal order if it consists of a sequence of preparation commands (N),
        followed by entanglement commands (E), followed by alternating layers of measurement (M)
        and correction (X, Z) commands, with no interleaving or reordering.

        Returns
        -------
        bool
            True if the pattern is in normal order, False otherwise.
        """
        current_section = CommandKind.N

        for cmd in self._commands:
            if cmd.kind == CommandKind.N:
                if current_section != CommandKind.N:
                    return False
            elif cmd.kind == CommandKind.E:
                if current_section == CommandKind.M or cmd.kind == CommandKind.X or cmd.kind == CommandKind.Z:
                    return False
                current_section = CommandKind.E
            elif cmd.kind == CommandKind.M:
                if current_section == CommandKind.X or cmd.kind == CommandKind.Z:
                    return False
                current_section = CommandKind.M
            elif cmd.kind in (CommandKind.X, CommandKind.Z):
                if current_section == CommandKind.N or current_section == CommandKind.E:
                    return False
                current_section = cmd.kind
            else:
                assert_never(cmd.kind)

        return True

    def __getitem__(self, key) -> Command:
        return self._commands[key]

    def __iter__(self) -> Iterator[Command]:
        return iter(self._commands)

    def __len__(self) -> int:
        return len(self._commands)

    def clone(self) -> "Pattern":
        """Return a deep copy of the pattern."""
        return Pattern(copy.deepcopy(self._commands), list(self._input_nodes))

    def set_measurements(self, overrides: Mapping[Node, tuple[float, float, float]]):
        """Override $(\\alpha, \\beta, \\gamma)$ of the listed ``M`` commands in place and return self.

        Parameters
        ----------
        overrides : Mapping[Node, tuple[float, float, float]]
            A mapping of node numbers to tuples of $(\\alpha, \\beta, \\gamma)$.

        Raises
        ------
        ValueError
            If any node listed in ``overrides`` has no ``M`` command.
        """
        seen: set[Node] = set()
        for cmd in self._commands:
            if cmd.kind == CommandKind.M and cmd.node in overrides:
                cmd.alpha, cmd.beta, cmd.gamma = overrides[cmd.node]
                seen.add(cmd.node)

        if missing := overrides.keys() - seen:
            raise ValueError(f"No measurement command found for node(s): {sorted(missing)}.")

    def set_squeezing(self, overrides: Mapping[Node, tuple[float, float]]) -> None:
        """Override $(r, \\theta)$ of the listed ``N`` commands in place.

        Parameters
        ----------
        overrides : Mapping[Node, tuple[float, float]]
            A mapping of node numbers to tuples of $(r, \\theta)$.

        Raises
        ------
        ValueError
            If any node listed in overrides has no ``N`` command.
        """
        seen: set[Node] = set()
        for cmd in self._commands:
            if cmd.kind == CommandKind.N and cmd.node in overrides:
                cmd.squeezing_ratio, cmd.squeezing_angle = overrides[cmd.node]
                seen.add(cmd.node)

        if missing := overrides.keys() - seen:
            raise ValueError(f"No preparation command found for node(s): {sorted(missing)}.")

    def reset(self):
        """Reset the pattern to a default state by clearing all measurements and corrections.
        The default state is not necessarily the original state.
        """
        for cmd in self._commands:
            if cmd.kind == CommandKind.M:
                cmd.alpha = cmd.beta = cmd.gamma = 0.0
            elif cmd.kind == CommandKind.N:
                cmd.squeezing_ratio = 2.0
                cmd.squeezing_angle = np.pi / 2

    def to_dict(self) -> dict:
        """Serialise this :class:`Pattern` to a JSON-friendly dict.

        Output shape: ``{"input_nodes": [...], "commands": [{"kind": ..., ...}, ...]}``.
        Each command is rendered with its kind tag and the fields relevant to
        that kind (e.g. ``squeezing_ratio`` for ``N``, ``alpha``/``beta``/
        ``gamma`` for ``M``, correction domains for ``M``/``X``/``Z``).
        """
        commands: list[dict] = []
        for cmd in self._commands:
            if cmd.kind == CommandKind.N:
                commands.append({
                    "kind": "N",
                    "node": cmd.node,
                    "squeezing_ratio": cmd.squeezing_ratio,
                    "squeezing_angle": cmd.squeezing_angle,
                })
            elif cmd.kind == CommandKind.E:
                commands.append({
                    "kind": "E",
                    "nodes": list(cmd.nodes),
                    "weight": cmd.weight,
                })
            elif cmd.kind == CommandKind.M:
                commands.append({
                    "kind": "M",
                    "node": cmd.node,
                    "alpha": cmd.alpha,
                    "beta": cmd.beta,
                    "gamma": cmd.gamma,
                    "x_domain": {str(k): v for k, v in cmd.x_domain.items()},
                    "z_domain": {str(k): v for k, v in cmd.z_domain.items()},
                })
            elif cmd.kind == CommandKind.X:
                commands.append({
                    "kind": "X",
                    "node": cmd.node,
                    "amplitude": cmd.amplitude,
                    "x_domain": {str(k): v for k, v in cmd.x_domain.items()},
                })
            elif cmd.kind == CommandKind.Z:
                commands.append({
                    "kind": "Z",
                    "node": cmd.node,
                    "amplitude": cmd.amplitude,
                    "z_domain": {str(k): v for k, v in cmd.z_domain.items()},
                })
        return {"input_nodes": sorted(self._input_nodes), "commands": commands}

    def __str__(self):
        num_commands = len(self._commands)
        width = len(str(num_commands))
        return "\n".join(f"{i+1:0{width}d}) {cmd}" for i, cmd in enumerate(self._commands))


def flow_to_pattern(graph: OpenGraph, g: dict[int, dict[int, float]], layer: dict[int, list[int]]) -> Pattern:
    """Convert an OpenGraph with a flow to a Pattern.

    This function takes a flow and converts it into a Pattern by generating
    the appropriate sequence of commands based on the flow structure. The
    conversion follows this order: node preparation (``N``), entanglement (``E``),
    measurements (``M``) by layer, and corrections (``X``, ``Z``) for each layer.

    Parameters
    ----------
    graph : OpenGraph
        The input graph containing the nodes and edges to be converted.
    g : dict[int, dict[int, float]]
        The flow correction mapping. For each measured node, maps to a
        dictionary of target nodes and their correction amplitudes.
        Structure: {measured_node: {target_node: amplitude}}.
    layer : dict[int, list[int]]
        The layering of nodes for measurement order. Maps layer numbers
        to lists of nodes that should be measured in that layer.
        Structure: {layer_num: [node1, node2, ...]}.

    Returns
    ------
    Pattern
        The resulting pattern corresponding to the input graph's flow,
        containing the complete sequence of commands (N, E, M, X, Z)
        that implement the measurement-based quantum computation.
    """
    if g == {} or layer == {}:
        raise ValueError("Flow mapping g and layer mapping cannot be empty. (Graph has no flow.)")

    command_list: list[Command] = []

    # Prepare all nodes
    for node_to_measure in graph.non_input_nodes:
        command_list.append(N(node_to_measure))  # type: ignore

    # Entangle according to the graph edges
    for node1, node2, weight in graph.edges:
        command_list.append(E((node1, node2), weight))

    measured_nodes = set()
    max_layer = max(layer.keys()) + 1
    for layer_idx in reversed(range(1, max_layer)):
        # Measure nodes in the current layer
        for node_to_measure in layer[layer_idx]:
            command_list.append(M(node_to_measure))
            measured_nodes.add(node_to_measure)

        # dict[node_receiving_correction, dict[node_to_correct, amplitude]]
        z_corrections: dict[Node, dict[Node, float]] = defaultdict(dict)
        x_corrections: dict[Node, dict[Node, float]] = defaultdict(dict)
        for node_to_correct in layer[layer_idx]:
            corrections = g.get(node_to_correct, {})

            for node_receiving, amplitude in corrections.items():
                x_corrections[node_receiving][node_to_correct] = amplitude

                # Z part applied on the neighbor of the node receiving the X correction
                for neighbour in graph.get_neighbours(node_receiving):
                    if neighbour != node_to_correct and neighbour not in measured_nodes:
                        z_corrections[neighbour][node_to_correct] = amplitude * graph[node_receiving, neighbour]

        for x_node, x_corr in x_corrections.items():
            command_list.append(X(x_node, 0, x_domain=x_corr))

        for z_node, z_corr in z_corrections.items():
            command_list.append(Z(z_node, 0, z_domain=z_corr))


    return Pattern(command_list, input_nodes=graph.input_nodes)